version: "3.7"
services:
    hub:
        image: selenium/hub:3.141.59-xenon
        ports:
            - "4444:4444"
    chrome:
        image: selenium/node-chrome:3.141.59-xenon
        volumes:
            - /dev/shm:/dev/shm
        environment:
            HUB_HOST: hub
            HUB_PORT: 4444
        deploy:
            replicas: 1
        entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: "fantasymanager"
            # So you don't have to use root, but you can if you like
            MYSQL_USER: "fantasymanager"
            # You can use whatever password you like
            MYSQL_PASSWORD: "fantasymanager"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        expose:
            # Opens port 3306 on the container
            - "3306"
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    activemq:
        image: webcenter/activemq:5.14.3
        ports:
            # mqtt
            - "1883:1883"
            # amqp
            - "5672:5672"
            # ui
            - "8161:8161"
            # stomp
            - "61613:61613"
            # ws
            - "61614:61614"
            # jms
            - "61616:61616"
        networks: [backing-services]
        volumes:
            [
                "activemq-data:/opt/activemq/conf",
                "activemq-data:/data/activemq",
                "activemq-data:/var/log/activemq",
            ]
        environment:
            ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
            ACTIVEMQ_ADMIN_LOGIN: admin
            ACTIVEMQ_ADMIN_PASSWORD: password
            ACTIVEMQ_WRITE_LOGIN: write
            ACTIVEMQ_WRITE_PASSWORD: password
            ACTIVEMQ_READ_LOGIN: read
            ACTIVEMQ_READ_PASSWORD: password
            ACTIVEMQ_JMX_LOGIN: jmx
            ACTIVEMQ_JMX_PASSWORD: password
            ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
            ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
            ACTIVEMQ_ENABLED_SCHEDULER: "true"
            ACTIVEMQ_MIN_MEMORY: 512
            ACTIVEMQ_MAX_MEMORY: 2048
# Names our volume
volumes:
    my-db:
    activemq-data:

networks:
    backing-services:
        driver: bridge
