INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Canavaro_tigers Aleix Nahum", "CT");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("puchisolutions PUCHIS", "Car");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("suma y sigue SUM(NBA)", "WIN");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Vamos Union", "GMP");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Rubinho's Team RUBINHOS", "Rub");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("RIVIERA's TEAM", "Toni");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Castefa Forever", "PATA");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("La banda del Mi litron", "Kike");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("California Dreams", "DREA");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Capitan Salami", "Etoo");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("xic de graeras", "KOPA");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Hobbit's Team HOBBITS", "OSC");

INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Team Perez", "PERE");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Team 2", "2");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Team 3", "3");
INSERT INTO FANTASY_TEAM (TEAM_NAME, ABBREV) VALUES ("Team 4", "4");
