server:
  port: 8090
  
logging:
  level:
    root: warn
    org.springframework.web: info
    org.hibernate: error
    es.fantasymanager: debug
  
spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fantasymanagerTest?useSSL=false
    username: fantasymanager
    password: fantasymanager
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.threadPool.threadCount: 5
  activemq:
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
    user: admin
    password: admin    
  jms:
    listener:
      concurrency: 2
      max-concurrency: 2

configuration:
  quartz:
    instanceId: ${random.int[1,99999]}      
    
scheduled:
  parser:
    statistics: 0 0 8 * * ? * # 8am
    news: 0 0/5 * * * ? * # cada 5 mins     
    
telegram:
  token: 714506880:AAEQrW0ifef2fDZzlFtlcHSuWHflNaIWN8I
  #chatId: fantasyManagerChannel
  newsChatId: -352055855
  transactionsChatId: -360686582
  tradesChatId: -360686582
 
selenium:
  leagueId: 511966
  url-recent-ativity: http://fantasy.espn.com/basketball/recentactivity?leagueId=${selenium.leagueId}
  url-league-rosters: http://fantasy.espn.com/basketball/league/rosters?leagueId=${selenium.leagueId}
  
---

spring:
  profiles: prod
  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fantasymanager?useSSL=false
    username: fantasymanager
    password: fantasymanager
  
selenium:
  leagueId: 97189