server:
  port: 8090
  
spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fantasymanager?useSSL=false
    username: fantasymanager
    password: fantasymanager
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.threadPool.threadCount: 5
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin    
  jms:
    listener:
      concurrency: 4
      max-concurrency: 4

configuration:
  quartz:
    instanceId: ${random.int[1,99999]}      
    
scheduled:
  parser:
    statistics: 0 0 7 * * ? # 7am once a day     